### ISSUE TITLE
TLS failed issue

### ISSUE THREAD

**Issue by tomhumphrey** [keeshux/passepartout-ios#18]
I'm unable to connect to my VPN with Passepartout due to a TLS issue. Have tested the ovpn file in the OpenVPN connect app and it works fine. Have attached debug log. What am I doing wrong?

[debug-20181029-135020.txt](https://github.com/keeshux/passepartout-ios/files/2525502/debug-20181029-135020.txt)

**Comment by keeshux** [comment]
Your client certificate key might be encrypted, which is currently unsupported. Please double check your `<key>` entry in the .ovpn file and see if says "ENCRYPTED" at the beginning.

**Comment by tomhumphrey** [comment]
You're right - Encrypted private key
