### ISSUE TITLE
how to get amount of data which was uploaded and downloaded? 

### ISSUE THREAD

**Issue by bizibizi** [keeshux/passepartout-ios#21]

**Comment by keeshux** [comment]
https://github.com/keeshux/passepartout-ios/blob/e880192be5b1dfaf085a0353164ddc42c0d73827/Passepartout-iOS/Scenes/ServiceViewController.swift#L343

**Comment by keeshux** [comment]
Anyway, not an issue.

**Comment by bizibizi** [comment]
Thank you for your help! Yes, I got that it works by method

        func requestBytesCount(completionHandler: @escaping ((UInt, UInt)?) -> Void) {

 Can you tell me please what’s "TunnelKitProvider.Message.dataCount.data" ?

And TunnelKit is solution for iOS12 only , can it work in prior versions?

**Comment by bizibizi** [comment]
okay, maybe you know some other libraries which can work for ios9?

**Comment by keeshux** [comment]
Dude, you're polluting a world of repos. I ask you to please stop right away.
